### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by bw2** [tprodanov/parascopy#2]
Hi I'm looking forward to trying this tool! 
It would be great if a Dockerfile and/or docker image with all dependencies was available so I wouldn't have to create one locally. 
If you're interested I could submit this as a PR.

**Comment by tprodanov** [comment]
Hi @bw2 

I was considering making a Docker container, but as I understood there is no convinient way to give the container access to the regular filesystem, which is required to get access to input/output files.
But I am not an expert on Docker, so please correct me if I am wrong. Also yes, you can submit a PR.
