### ISSUE TITLE
Error in conda env with numpy

### ISSUE THREAD

**Issue by pabloangulo7** [tprodanov/parascopy#3]
Hello,

I have an error when I run the command: parascopy table -i pretable.bed.gz -f genome.fasta -o table.bed.gz
It seems the error is related with numpy and a deprecated function in the new version.

I am running the program in a conda environment created with:
conda create --name paras_env parascopy
conda activate paras_env

Could you tell me what is causing the error and how to fix it?

Thanks in advance

Pablo

![error](https://user-images.githubusercontent.com/70705390/215118114-6f4cfff0-0fac-4bf1-9e2e-541831c390dd.png)

**Comment by tprodanov** [comment]
Hi Pablo,

Thank you for using Parascopy.
Yes, seems like `np.bool` was deprecated. I replaced it with `np.bool_` in a new release, but it may take a couple days to update on bioconda. Otherwise, you can clone this repository and run `python setup.py develop --no-deps`.

Best regards,
Timofey
