### ISSUE TITLE
Display error missing area file

### ISSUE THREAD

**Issue by zshu-alt** [tprodanov/parascopy#7]
Hello, I used parascopy to successfully run the read depth step, but an error occurred when I ran the Estimate agCN and psCN step. My code is as follows:
parascopy cn -I /home/project/muscle/WGS/parascopy/input_list.txt -t /home/database/GRCh37/table_GRCh37.bed.gz -f  /home/database/GRCh37/Homo_sapiens.GRCh37.dna_sm.primary_assembly.fa -R /home/database/jinyu_wes.bed -d depth -o  analysis1
The error is as follows:
Traceback (most recent call last):
File "/home/dell/miniconda3/envs/wgs/bin/parascopy", line 10, in
sys.exit(main())
The File "/ home/dell/miniconda3 / envs/WGS/lib/python3.10 / site - packages/parascopy/entry_point py", line 121, in the main
return _process_exceptions(detect_cn.main, inner_prog, inner_argv, is_new)
File "/ home/dell/miniconda3 envs WGS/lib/python3.10 / site - packages/parascopy/entry_point. Py", line 70, in _process_exceptions
fn(*args, **kwargs)
The File "/ home/dell/miniconda3 / envs/WGS/lib/python3.10 / site - packages/parascopy detect_cn. Py", line 1066, in the main
regions, loaded_models = get_regions(args, genome, load_models=not args.is_new)
The File "/ home/dell/miniconda3 / envs/WGS/lib/python3.10 / site - packages/parascopy detect_cn. Py", line 753, in get_regions
return (common.get_regions(args, genome), None)
The File "/ home/dell/miniconda3 / envs/WGS/lib/python3.10 / site - packages/parascopy/inner/common. Py", line 229, in get_regions
return get_regions_explicit(args.regions, args.regions_file, genome, only_unique)
The File "/ home/dell/miniconda3 / envs/WGS/lib/python3.10 / site - packages/parascopy/inner/common. Py", line 223, in get_regions_explicit
raise errors.EmptyResult(
parascopy.inner.errors.EmptyResult: No regions provided!  Please specify -r  [ ...]  or -R  [ ...]
This indicates that I don't seem to have my region file, but I've already written the parameters
Use another command -r:
parascopy cn -I /home/project/muscle/WGS/parascopy/input_list.txt -t /home/database/GRCh37/table_GRCh37.bed.gz -f  /home/database/GRCh37/Homo_sapiens.GRCh37.dna_sm.primary_assembly.fa -d depth -r chr5:70220768-70248842::SMN1 -o  analysis1
The error is still displayed:

The File "/ home/dell/miniconda3 / envs/WGS/lib/python3.10 / site - packages/parascopy/inner/genome. Py", line 295, in the parse
chrom_id = genome.chrom_id(m.group(1))
The File "/ home/dell/miniconda3 / envs/WGS/lib/python3.10 / site - packages/parascopy/inner/genome. Py", 48, the line in chrom_id
return self._ids[chrom_name]
KeyError: 'chr5'
I am sure I have the right to read and write my region bed file. How can I solve this problem?
I would appreciate it if you could help me.

**Comment by tprodanov** [comment]
Sorry for the long delay!
Could the problem be in that the reference genome has chromosome names "1", "2", ..., and not "chr1", "chr2", and so on?
